### ISSUE TITLE
Hierapolis integration

### ISSUE THREAD

**Issue by krmbzds** [yakut-project/yakut-old#18]

**Comment by utdemir** [comment]
Implemented Hierapolis stylesheets with fba41fc39b41631c808994b51261b3cb23f28391 merge. I included stylesheets to management layout and sidebar(dock). The additional features should also be implemented when adding new elements from Hierapolis.

**Comment by krmbzds** [comment]
:bug:  `navbar` overlaps with `sidebar`.

![overlap](https://f.cloud.github.com/assets/1383035/1049562/6587e51c-10a8-11e3-82d5-4b03ab770570.png)
