### ISSUE TITLE
Decide which gems to use

### ISSUE THREAD

**Issue by krmbzds** [yakut-project/yakut-old#2]

**Comment by marjinal1st** [comment]
My suggestions:
- Paperclip (File uploading)
- Zeus (Fast startup for server)
- Annotate (Model schemas in model files)
- Pry (IRB alternative)

**Comment by krmbzds** [comment]
These are the additional gems we're currently using:

``` rb
gem 'devise'
gem 'devise-i18n'

gem 'haml-rails'
gem 'simple_form'

gem 'bootstrap-sass-rails', '~> 3.0.0'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
end
```

**Comment by krmbzds** [comment]
We can use this gem:

``` rb
gem "enumerize", "~> 0.7.0"
```

Homepage: https://rubygems.org/gems/enumerize
